version: '3.4'

services:
  postgres:
    container_name: cocktails-postgres-${CONTAINER_NS}
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: ${COCKTAILS__DB_USER}
      POSTGRES_DB: ${COCKTAILS__DB_DATABASE}
      POSTGRES_PASSWORD: ${COCKTAILS__DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${COCKTAILS__DB_PORT}:5432"
    volumes:
      - ${COCKTAILS__PGDATA_PATH}:/var/lib/postgresql/data/pgdata

  server:
    container_name: cocktails-server-${CONTAINER_NS}
    image: registry.fritsler.ru/cocktail-library-server:${BUILD_VER}
    restart: always
    env_file:
      - .env
    links:
      - postgres
    ports:
      - "${COCKTAILS__SERVER_PORT}:6000"

  metabase:
    container_name: cocktails-metabase-${CONTAINER_NS}
    image: metabase/metabase:latest
    restart: always
    volumes:
      - ../metabase-data:/metabase-data
    ports:
      - "${COCKTAILS__METABASE_PORT}:3000"
    env_file:
      - .env
